#Son Kullanılan DockerCompose Dosyası
version: '3.3'
  
services:
      sonarqube:
    image: sonarqube:7.6-community 
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    networks:
      - sonarnet
    ports:
      - '9000:9000'
    environment:
      - sonar.jdbc.username=sonar
      - sonar.jdbc.password=sonar
      - sonar.jdbc.url=jdbc:postgresql://db:5432/sonar
      
  currency-conversion:
     image: currency-conversion
     restart: always
     container_name: currency-conversion
     build:
       context: .
       dockerfile: Dockerfile-CC
     ports:       
       - "8100:8100"
       - "1022:22"
     networks:
       - transfer-market
     hostname: currency-conversion
        
  currency-exchange :
     image: currency-exchange
     restart: always
     container_name: currency-exchange     
     build:
       context: .
       dockerfile: Dockerfile-CE
     ports:
       - "8000:8000"       
       - "1023:22"
     networks:
       - transfer-market
     hostname: currency-exchange

networks:
  transfer-market:
    driver: bridge
